name: Deploy 

on:
  push:
    branches: 
      - main

jobs:
  build-and-push:
    name: build and upload image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aws-cicd:latest

  deploy:
    needs: [build-and-push]
    name: deploy image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Copy Docker Compose & Script to Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # port: ${{ secrets.SSH_PORT }}
          source: 'docker/docker-compose.yaml,scripts/deploy.sh'
          target: '/home/ubuntu'

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # port: ${{ secrets.SSH_PORT }}
          script: sh /home/ubuntu/scripts/deploy.sh
