version: '3.8'

services:
  mysql:
    image: mysql:8.0  # version of mysql you want to use
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      # MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"   # map the mysql port to your local machine
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network: